checkPositiveData <- function(A, B) stopifnot(A >= 0, B >= 0)
checkNotZeroData <- function(A, B) stopifnot(A != 0, B != 0)
checkBinomialData <- function(A, B) stopifnot(A %in% c(0, 1), B %in% c(0, 1))
checkIntegerData <- function(A, B) stopifnot(as.integer(A) == A, as.integer(B) == B)

checkGammaPriors <- function(shape, rate, ...) stopifnot(shape > 0, rate > 0)
checkNormalPriors <- function(mu, sd, ...) stopifnot(sd > 0)
checkInvGammaPriors <- function(shape, scale, ...) stopifnot(shape > 0, scale > 0)
checkBetaPriors <- function(alpha, beta, ...) stopifnot(alpha > 0, beta > 0)
checkParetoPriors <- function(xm, alpha, ...) stopifnot(xm > 0, alpha > 0)
