# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alt_count <- function(alpha_1, beta_1, alpha_2, beta_2) {
    .Call('bayesAB_alt_count', PACKAGE = 'bayesAB', alpha_1, beta_1, alpha_2, beta_2)
}

alt_prop <- function(alpha_1, beta_1, alpha_2, beta_2) {
    .Call('bayesAB_alt_prop', PACKAGE = 'bayesAB', alpha_1, beta_1, alpha_2, beta_2)
}

rcpp_hello_world <- function() {
    .Call('bayesAB_rcpp_hello_world', PACKAGE = 'bayesAB')
}

