# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bayesPoissonTestClosed_ <- function(alpha_1, beta_1, alpha_2, beta_2) {
    .Call('bayesAB_bayesPoissonTestClosed_', PACKAGE = 'bayesAB', alpha_1, beta_1, alpha_2, beta_2)
}

bayesBernoulliTestClosed_ <- function(alpha_1, beta_1, alpha_2, beta_2) {
    .Call('bayesAB_bayesBernoulliTestClosed_', PACKAGE = 'bayesAB', alpha_1, beta_1, alpha_2, beta_2)
}

